### ISSUE TITLE
Métodos de aresta Alvo

### ISSUE THREAD

**Issue by renanNun** [renanNun/Trabalho-de-Grafos#2]
`No* Aresta::getNoAlvo(){
    return this->alvo;
}

void Aresta::setNoAlvo(No* noAlvo){
    this->alvo = noAlvo;
}`

Eu não faço ideia do que esse método faz direito, poderia me explicar?
Tipo a gente já guarda o Id do Vértice. Não estaríamos fazendo trabalho duplicado?

**Comment by LucasRibP** [comment]
Então, isso é do que te falei, de parar de salvar o id do no e passar a salvar um ponteiro pro no. Se a gnt fizer desse jeito n precisa percorrer a lista pra achar o id toda vez

**Comment by renanNun** [comment]
Então vamos ter que implementar uma busca para fazer isso mais eficientemente.

**Comment by LucasRibP** [comment]
Cada no tem uma lista de arestas, esse alvo é onde as arestas tão conectados

**Comment by renanNun** [comment]
Faz sentido, vou tentar trabalhar com isso então. Obrigado pelas respostas, vou fechar a issue.
